language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/1up-darwin-amd64
          - cross/1up-darwin-amd64.md5
          - cross/1up-darwin-amd64.sha256
          - cross/1up-darwin-386
          - cross/1up-darwin-386.md5
          - cross/1up-darwin-386.sha256
          - cross/1up-freebsd-amd64
          - cross/1up-freebsd-amd64.md5
          - cross/1up-freebsd-amd64.sha256
          - cross/1up-freebsd-386
          - cross/1up-freebsd-386.md5
          - cross/1up-freebsd-386.sha256
          - cross/1up-linux-arm
          - cross/1up-linux-arm.md5
          - cross/1up-linux-arm.sha256
          - cross/1up-linux-arm64
          - cross/1up-linux-arm64.md5
          - cross/1up-linux-arm64.sha256
          - cross/1up-linux-amd64
          - cross/1up-linux-amd64.md5
          - cross/1up-linux-amd64.sha256
          - cross/1up-linux-386
          - cross/1up-linux-386.md5
          - cross/1up-linux-386.sha256
          - cross/1up-solaris-amd64
          - cross/1up-solaris-amd64.md5
          - cross/1up-solaris-amd64.sha256
          - cross/1up-windows-amd64
          - cross/1up-windows-amd64.md5
          - cross/1up-windows-amd64.sha256
          - cross/1up-windows-386
          - cross/1up-windows-386.md5
          - cross/1up-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "YvaRO11fjMBn9zd3L4xgstDOpg0jAKYcHQntihWJQczt9pTwWhl3gqNy3BhRLXVpUJtMsGmbQPHmhvs58MqEVbrBnuMZCsQPSGir1siqTPtONr1EvdESUsKaEIGeC6vddCpBcTP1IKZ5pYpx27r517VjJr5fSqZQrJaQ7zn5aK+ez2MNiJTUhlIdKxBJk3BNN4IUqmQaNqfhbUuWfGJumdb0dSJhhPMywULS4cMkUUlR5s1YdyfuYIwqaF3jZFKCD4Q24/ac7ecIacE44vpaTQDgrqm2OEfGGYSUoeyQ9wATe4W101KUMAXSFshtcKTKp3MN+weK3FkBYg1odM+KtYJOPZYam4wwmWPpAkCRswLBXSmGueftz1JzkvqtYQ6gcXA08/auPDjvxwo2p55u5X3tGPYkzH2rEGUVSjJj+efEOSubz1lFlDGUly/ZmuMfJQht29lkVAqm4MTIPopKS3WstEXnWJpQmliIRowTN+vJUJufknw/4XcDi+KC02CNg1SfF7UcvtU2pJVf20IopP/TU8GnhtmlsMN/GCFbiSM1kSeicJf/Dkyc7S3KZyRUnZHCrDnvLOYV+zX+q7vqUu4DwWz8/c0qxWhQezgvzjFKL6+Crhey42VpbYGSABmJjE/TpljfLy62Dcl95evlEW8hNCz58G7lOrMnITSh5yY="
